### PR TITLE
Fixes for dmd 2.076.0.

### PR DESCRIPTION
**Pull request by kntroh**
I commented out the code that uses `TypeInfo_Typedef`.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
👌.

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by jacob-carlborg** [comment]
@kntroh I've forgot to mention this, but I've inlined all the submodules directly in the main repository in preparation for Dub support. This repository and the other ones (Windows, Linux and Snippets) are not used anymore.

**Comment by kntroh** [comment]
I will follow. Thanks.

**Pull request merged**
